baseURL = '/'
languageCode = 'en-us'
title = 'falconite'
theme = "nightfall"
# description = "Welcome to my humble abode."
publishDir = "../public"
summaryLength = 15
enableRobotsTXT = true
[params]

author = "pspiagicw"
user = "pspiagicw"
hostname = "falconite"
published = true
readingTime = true

footerHtml = 'Made with ♥  using Hugo.'

[[params.social]]
name = "github"
url = "https://github.com/pspiagicw"
icon = "fa-brands fa-github"

[[params.social]]
name = "email"
url = "mailto:pspiagicw@gmail.com"
icon = "fa-regular fa-envelope"

[menu]

[[menu.header]]
name = "home"
url = "/"
weight = 1

[[menu.header]]
name = "writing"
url = "/posts"
weight = 2

[[menu.header]]
name = "about"
url = "/about"
weight = 3

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = 'prefix'
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'catppuccin-mocha'
    tabWidth = 4

[related]
  threshold = 10
  includeNewer = true
  toLower = true
  
  [[related.indices]]
    name = "tags"
    weight = 90
