baseURL = '/'
languageCode = 'en-us'
title = 'falconite'
theme = "nightfall"
# description = "Welcome to my humble abode."
publishDir = "../public"
summaryLength = 15
[params]

author = "pspiagicw"
user = "pspiagicw"
hostname = "falconite"

footerHtml = 'Made with ♥  using Hugo.'

[[params.social]]
name = "github"
url = "https://github.com/pspiagicw"
# icon = "fa-brands fa-github"

[[params.social]]
name = "email"
url = "mailto:pspiagicw@gmail.com" # no need for "mailto:" at the start

[menu]

[[menu.header]]
name = "home"
url = "/"
weight = 1

[[menu.header]]
name = "writing"
url = "/posts"
weight = 2

[[menu.header]]
name = "about"
url = "/about"
weight = 3
