#!/bin/bash
#

myProjects=("dotback" "qemantra" "sinister" "groom" "hotshot")

for project in ${myProjects[@]}; do
    rm -rf content/$project
    git clone --depth 1 https://github.com/pspiagicw/$project content/$project
    rm -rf content/$project/.git
    mv content/$project/README.md content/$project/index.md
    sed -i "s|\./gif|/$project/gif|" content/$project/index.md
done
