#!/bin/bash
#

myProjects=("qemantra" "hotshot" "sinister" "groom" "dotback" "fener" "kato")

for project in ${myProjects[@]}; do
    rm -rf content/$project
    mkdir content/$project
    pushd content/$project
    wget https://raw.githubusercontent.com/pspiagicw/$project/main/README.md
    popd
    mv content/$project/README.md content/$project/index.md
    sed -i "s|\./gif|/$project/gif|" content/$project/index.md
    sed -i 's/> \[!NOTE\]//' content/$project/index.md
    sed -i 's/> \[!IMPORTANT\]//' content/$project/index.md
    sed -i 's/> \[!WARNING\]//' content/$project/index.md
    sed -i 's/> \[!TIP\]//' content/$project/index.md
    sed -i 's/> \[!CAUTION\]//' content/$project/index.md
    sed -i "1i +++\ntitle = '$project'\nauthor = 'pspiagicw'\ndate = $(date '+%F')\n+++\n" content/$project/index.md
done
